/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    branches: Branch;
    groups: Group;
    players: Player;
    'training-sessions': TrainingSession;
    consents: Consent;
    'login-tokens': LoginToken;
    devices: Device;
    notifications: Notification;
    rsvps: Rsvp;
    announcements: Announcement;
    questions: Question;
    'question-messages': QuestionMessage;
    matches: Match;
    subscriptions: Subscription;
    'chat-topics': ChatTopic;
    'chat-messages': ChatMessage;
    'chat-reads': ChatRead;
    'payment-threads': PaymentThread;
    'payment-messages': PaymentMessage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    branches: BranchesSelect<false> | BranchesSelect<true>;
    groups: GroupsSelect<false> | GroupsSelect<true>;
    players: PlayersSelect<false> | PlayersSelect<true>;
    'training-sessions': TrainingSessionsSelect<false> | TrainingSessionsSelect<true>;
    consents: ConsentsSelect<false> | ConsentsSelect<true>;
    'login-tokens': LoginTokensSelect<false> | LoginTokensSelect<true>;
    devices: DevicesSelect<false> | DevicesSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    rsvps: RsvpsSelect<false> | RsvpsSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    questions: QuestionsSelect<false> | QuestionsSelect<true>;
    'question-messages': QuestionMessagesSelect<false> | QuestionMessagesSelect<true>;
    matches: MatchesSelect<false> | MatchesSelect<true>;
    subscriptions: SubscriptionsSelect<false> | SubscriptionsSelect<true>;
    'chat-topics': ChatTopicsSelect<false> | ChatTopicsSelect<true>;
    'chat-messages': ChatMessagesSelect<false> | ChatMessagesSelect<true>;
    'chat-reads': ChatReadsSelect<false> | ChatReadsSelect<true>;
    'payment-threads': PaymentThreadsSelect<false> | PaymentThreadsSelect<true>;
    'payment-messages': PaymentMessagesSelect<false> | PaymentMessagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Контакт тренера/родителя. 152-ФЗ: минимизация — только для связи.
   */
  phone?: string | null;
  roles: ('owner' | 'admin' | 'coach' | 'parent' | 'child')[];
  /**
   * Только для детского входа; взрослые входят по email/VK.
   */
  login?: string | null;
  /**
   * SSO-провайдер, через который связан аккаунт. Пусто — вход по email.
   */
  authProvider?: 'radar' | null;
  /**
   * Стабильный идентификатор личности у провайдера (sub Радара).
   */
  externalId?: string | null;
  /**
   * Филиал участника — граница видимости. Пусто — только у владельцев сети.
   */
  branch?: (number | null) | Branch;
  status: 'pending' | 'approved';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branches".
 */
export interface Branch {
  id: number;
  name: string;
  city?: string | null;
  operatorName?: string | null;
  operatorLegalForm?: string | null;
  operatorInn?: string | null;
  operatorAddress?: string | null;
  operatorEmail?: string | null;
  operatorPhone?: string | null;
  operatorResponsiblePerson?: string | null;
  processorAgreementSignedAt?: string | null;
  /**
   * Справочная дата. Уведомление подаёт школа-оператор, не платформа.
   */
  rknNotifiedAt?: string | null;
  /**
   * Реквизиты и инструкция для родителей: куда и как платить, сколько стоит абонемент. Показываются родителю на экране «Оплата».
   */
  paymentDetails?: string | null;
  /**
   * Цена по умолчанию для всех групп филиала. Родитель видит её как «к оплате», когда абонемент кончается или уже просрочен. У отдельной группы цену можно задать свою.
   */
  monthlyFee?: number | null;
  /**
   * Необязательно: ссылка/QR-цель, открывающая форму оплаты с реквизитами.
   */
  paymentUrl?: string | null;
  /**
   * Снять галочку = закрыть филиал, не удаляя его историю.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups".
 */
export interface Group {
  id: number;
  name: string;
  /**
   * Кто ведёт группу. Тренер видит и правит только свои группы.
   */
  coaches?: (number | User)[] | null;
  description?: string | null;
  /**
   * Филиал группы. Определяет, кто вообще видит её расписание, объявления и детей.
   */
  branch: number | Branch;
  /**
   * Цена именно этой группы. Пусто — берётся цена филиала. Родитель видит её как «к оплате».
   */
  monthlyFee?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 152-ФЗ: минимизация. Только имя + группа + контакт родителя. Без дат рождения, фото, здоровья, адресов, СНИЛС.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players".
 */
export interface Player {
  id: number;
  name: string;
  /**
   * Только для возрастной группы; не показывается участникам чатов.
   */
  dateOfBirth?: string | null;
  group: number | Group;
  /**
   * Аккаунт родителя — контакт и адресат уведомлений. Привязывается сам, когда родитель принимает приглашение по ссылке.
   */
  parent?: (number | null) | User;
  /**
   * Создаётся родителем в разделе «Аккаунт».
   */
  account?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-sessions".
 */
export interface TrainingSession {
  id: number;
  group: number | Group;
  startDate: string;
  endDate?: string | null;
  location?: string | null;
  /**
   * Изменение или отмена сразу рассылает уведомление родителям группы.
   */
  status: 'planned' | 'changed' | 'cancelled';
  note?: string | null;
  /**
   * Список реально изменившихся полей последней волны (служебное).
   */
  changedFields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Метка последней значимой правки. Coverage и снимок в Notifications.changedAt.
   */
  changedAt?: string | null;
  prevStartDate?: string | null;
  prevLocation?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Юридическая запись согласия на обработку ПДн ребёнка (152-ФЗ). Доступ — только персонал и сам родитель.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consents".
 */
export interface Consent {
  id: number;
  parent: number | User;
  players?: (number | Player)[] | null;
  /**
   * Обязательно. Осознанное согласие законного представителя ребёнка.
   */
  consentGiven: boolean;
  confirmedRepresentative?: boolean | null;
  /**
   * Версия текста согласия/политики на момент подписания (G7 `_v`).
   */
  policyVersion: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "login-tokens".
 */
export interface LoginToken {
  id: number;
  tokenHash: string;
  purpose: 'login' | 'invite';
  email?: string | null;
  user?: (number | null) | User;
  player?: (number | null) | Player;
  expiresAt: string;
  usedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Web-push подписки. Адрес доставки best-effort пуша. Доступ — только свой владелец.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "devices".
 */
export interface Device {
  id: number;
  user: number | User;
  endpoint: string;
  p256dh: string;
  auth: string;
  /**
   * Для диагностики протухания подписки (особенно iOS).
   */
  platform?: string | null;
  userAgent?: string | null;
  lastSuccessAt?: string | null;
  /**
   * Dead-letter: при 410/404 запись удаляется сервисом отправки.
   */
  failureCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Очередь неподтверждённых изменений у родителя. Главная гарантия, что до родителя дошло: работает и без пуш-уведомлений. Отсюда же сводка тренеру «приняли N из M».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  session: number | TrainingSession;
  parent: number | User;
  /**
   * Какие дети этого родителя затронуты. В текст пуш-уведомления имена детей не попадают.
   */
  players: (number | Player)[];
  type: 'changed' | 'cancelled';
  /**
   * Доставлено → открыто → подтверждено. Родитель может только подтвердить; «устарело» проставляется само, когда приходит более свежее изменение по той же тренировке.
   */
  status: 'delivered' | 'seen' | 'acked' | 'superseded';
  /**
   * Снимок session.changedAt. Coverage сверяет с текущей волной сессии.
   */
  changedAt: string;
  /**
   * Диагностика best-effort. Не корректность.
   */
  pushSentAt?: string | null;
  pushResult?: ('ok' | 'failed' | 'skipped') | null;
  seenAt?: string | null;
  ackedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Кто придёт на тренировку: один ответ на каждого ребёнка. Сводка — на экране тренера.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rsvps".
 */
export interface Rsvp {
  id: number;
  session: number | TrainingSession;
  player: number | Player;
  parent: number | User;
  response: 'going' | 'not_going';
  /**
   * Служебное: по нему напоминание уходит только тем, кто ещё не ответил.
   */
  respondedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Новости тренера группе / владельца сети. Не ack-очередь. Пуш — только по флагу.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: number;
  author?: (number | null) | User;
  /**
   * Филиалы/сеть — только владелец. Группа — классическое объявление тренера.
   */
  scope: 'group' | 'branch' | 'network';
  /**
   * Кому адресовано при охвате «Выбранные филиалы».
   */
  branches?: (number | Branch)[] | null;
  /**
   * Закреплённое объявление показывается сверху ленты. Только владелец.
   */
  pinned?: boolean | null;
  group?: (number | null) | Group;
  title: string;
  /**
   * 152-ФЗ: массовая рассылка — без персональных данных детей в тексте.
   */
  body: string;
  /**
   * best-effort, normal-приоритет. Пуш уходит ОДИН раз — на создании (granularity §6).
   */
  triggersPush?: boolean | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Личные вопросы родителей тренеру: родитель спрашивает — тренер читает и отвечает.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions".
 */
export interface Question {
  id: number;
  parent: number | User;
  group: number | Group;
  session?: (number | null) | TrainingSession;
  body: string;
  /**
   * new→read→answered. Двигает тренер через инбокс.
   */
  status: 'new' | 'read' | 'answered';
  readAt?: string | null;
  answeredAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Переписка внутри вопроса: сам вопрос — в разделе «Вопросы», здесь — ответы и реплики.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "question-messages".
 */
export interface QuestionMessage {
  id: number;
  question: number | Question;
  group: number | Group;
  parent: number | User;
  author?: (number | null) | User;
  authorRole: 'parent' | 'coach';
  body: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Расписание игр и результаты — информационный раздел: подтверждения от родителей здесь не запрашиваются. Счёт пуст = будущий матч.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches".
 */
export interface Match {
  id: number;
  group: number | Group;
  matchDate: string;
  opponent: string;
  homeAway: 'home' | 'away';
  location?: string | null;
  scoreOur?: number | null;
  scoreOpponent?: number | null;
  /**
   * Только имя ребёнка — из справочника «Дети». Видно родителям группы. Заполняется у сыгранного матча.
   */
  scorers?:
    | {
        player: number | Player;
        goals: number;
        id?: string | null;
      }[]
    | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Учёт оплат абонементов. Продление = новая запись; статус выводится по датам.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions".
 */
export interface Subscription {
  id: number;
  player: number | Player;
  paidFrom?: string | null;
  paidUntil: string;
  amount?: number | null;
  /**
   * Например: «перенос из-за болезни», «скидка на второго ребёнка».
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Темы общих чатов групп: тренеры и родители одной группы. Тему заводит тренер, писать в неё могут все участники группы.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-topics".
 */
export interface ChatTopic {
  id: number;
  room: 'adults' | 'children';
  /**
   * О чём разговор — например, «Едем на соревнования 12 сентября».
   */
  title: string;
  group: number | Group;
  createdBy?: (number | null) | User;
  /**
   * Проставляется сама при новом сообщении — по ней темы идут сверху вниз.
   */
  lastMessageAt?: string | null;
  /**
   * Закрытую тему видно, но написать в неё нельзя. Удобно для разъехавшихся разговоров.
   */
  closed?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Сообщения в темах общих чатов. Заводить и править вручную не нужно — пишутся из приложения.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-messages".
 */
export interface ChatMessage {
  id: number;
  room: 'adults' | 'children';
  topic: number | ChatTopic;
  /**
   * Копируется с темы — по ней считается видимость.
   */
  group: number | Group;
  author?: (number | null) | User;
  /**
   * Снимок имени на момент отправки — переписка переживает удаление аккаунта.
   */
  authorName?: string | null;
  authorRole?: ('coach' | 'staff' | 'parent' | 'child') | null;
  body: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Служебное: кто до какого момента прочитал тему. Заполняется само при открытии темы.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-reads".
 */
export interface ChatRead {
  id: number;
  user: number | User;
  topic: number | ChatTopic;
  lastReadAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Неудаляемые личные диалоги родителей с бухгалтерией. Ведутся из приложения.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-threads".
 */
export interface PaymentThread {
  id: number;
  parent: number | User;
  branch?: (number | null) | Branch;
  lastMessageAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * История неизменяема и не удаляется.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-messages".
 */
export interface PaymentMessage {
  id: number;
  thread: number | PaymentThread;
  author?: (number | null) | User;
  authorName: string;
  authorRole: 'parent' | 'staff';
  body: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'branches';
        value: number | Branch;
      } | null)
    | ({
        relationTo: 'groups';
        value: number | Group;
      } | null)
    | ({
        relationTo: 'players';
        value: number | Player;
      } | null)
    | ({
        relationTo: 'training-sessions';
        value: number | TrainingSession;
      } | null)
    | ({
        relationTo: 'consents';
        value: number | Consent;
      } | null)
    | ({
        relationTo: 'login-tokens';
        value: number | LoginToken;
      } | null)
    | ({
        relationTo: 'devices';
        value: number | Device;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'rsvps';
        value: number | Rsvp;
      } | null)
    | ({
        relationTo: 'announcements';
        value: number | Announcement;
      } | null)
    | ({
        relationTo: 'questions';
        value: number | Question;
      } | null)
    | ({
        relationTo: 'question-messages';
        value: number | QuestionMessage;
      } | null)
    | ({
        relationTo: 'matches';
        value: number | Match;
      } | null)
    | ({
        relationTo: 'subscriptions';
        value: number | Subscription;
      } | null)
    | ({
        relationTo: 'chat-topics';
        value: number | ChatTopic;
      } | null)
    | ({
        relationTo: 'chat-messages';
        value: number | ChatMessage;
      } | null)
    | ({
        relationTo: 'chat-reads';
        value: number | ChatRead;
      } | null)
    | ({
        relationTo: 'payment-threads';
        value: number | PaymentThread;
      } | null)
    | ({
        relationTo: 'payment-messages';
        value: number | PaymentMessage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  roles?: T;
  login?: T;
  authProvider?: T;
  externalId?: T;
  branch?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branches_select".
 */
export interface BranchesSelect<T extends boolean = true> {
  name?: T;
  city?: T;
  operatorName?: T;
  operatorLegalForm?: T;
  operatorInn?: T;
  operatorAddress?: T;
  operatorEmail?: T;
  operatorPhone?: T;
  operatorResponsiblePerson?: T;
  processorAgreementSignedAt?: T;
  rknNotifiedAt?: T;
  paymentDetails?: T;
  monthlyFee?: T;
  paymentUrl?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups_select".
 */
export interface GroupsSelect<T extends boolean = true> {
  name?: T;
  coaches?: T;
  description?: T;
  branch?: T;
  monthlyFee?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players_select".
 */
export interface PlayersSelect<T extends boolean = true> {
  name?: T;
  dateOfBirth?: T;
  group?: T;
  parent?: T;
  account?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-sessions_select".
 */
export interface TrainingSessionsSelect<T extends boolean = true> {
  group?: T;
  startDate?: T;
  endDate?: T;
  location?: T;
  status?: T;
  note?: T;
  changedFields?: T;
  changedAt?: T;
  prevStartDate?: T;
  prevLocation?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consents_select".
 */
export interface ConsentsSelect<T extends boolean = true> {
  parent?: T;
  players?: T;
  consentGiven?: T;
  confirmedRepresentative?: T;
  policyVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "login-tokens_select".
 */
export interface LoginTokensSelect<T extends boolean = true> {
  tokenHash?: T;
  purpose?: T;
  email?: T;
  user?: T;
  player?: T;
  expiresAt?: T;
  usedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "devices_select".
 */
export interface DevicesSelect<T extends boolean = true> {
  user?: T;
  endpoint?: T;
  p256dh?: T;
  auth?: T;
  platform?: T;
  userAgent?: T;
  lastSuccessAt?: T;
  failureCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  session?: T;
  parent?: T;
  players?: T;
  type?: T;
  status?: T;
  changedAt?: T;
  pushSentAt?: T;
  pushResult?: T;
  seenAt?: T;
  ackedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rsvps_select".
 */
export interface RsvpsSelect<T extends boolean = true> {
  session?: T;
  player?: T;
  parent?: T;
  response?: T;
  respondedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  author?: T;
  scope?: T;
  branches?: T;
  pinned?: T;
  group?: T;
  title?: T;
  body?: T;
  triggersPush?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions_select".
 */
export interface QuestionsSelect<T extends boolean = true> {
  parent?: T;
  group?: T;
  session?: T;
  body?: T;
  status?: T;
  readAt?: T;
  answeredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "question-messages_select".
 */
export interface QuestionMessagesSelect<T extends boolean = true> {
  question?: T;
  group?: T;
  parent?: T;
  author?: T;
  authorRole?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches_select".
 */
export interface MatchesSelect<T extends boolean = true> {
  group?: T;
  matchDate?: T;
  opponent?: T;
  homeAway?: T;
  location?: T;
  scoreOur?: T;
  scoreOpponent?: T;
  scorers?:
    | T
    | {
        player?: T;
        goals?: T;
        id?: T;
      };
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions_select".
 */
export interface SubscriptionsSelect<T extends boolean = true> {
  player?: T;
  paidFrom?: T;
  paidUntil?: T;
  amount?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-topics_select".
 */
export interface ChatTopicsSelect<T extends boolean = true> {
  room?: T;
  title?: T;
  group?: T;
  createdBy?: T;
  lastMessageAt?: T;
  closed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-messages_select".
 */
export interface ChatMessagesSelect<T extends boolean = true> {
  room?: T;
  topic?: T;
  group?: T;
  author?: T;
  authorName?: T;
  authorRole?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-reads_select".
 */
export interface ChatReadsSelect<T extends boolean = true> {
  user?: T;
  topic?: T;
  lastReadAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-threads_select".
 */
export interface PaymentThreadsSelect<T extends boolean = true> {
  parent?: T;
  branch?: T;
  lastMessageAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-messages_select".
 */
export interface PaymentMessagesSelect<T extends boolean = true> {
  thread?: T;
  author?: T;
  authorName?: T;
  authorRole?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}