/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    groups: Group;
    players: Player;
    'training-sessions': TrainingSession;
    consents: Consent;
    'login-tokens': LoginToken;
    devices: Device;
    notifications: Notification;
    rsvps: Rsvp;
    announcements: Announcement;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    groups: GroupsSelect<false> | GroupsSelect<true>;
    players: PlayersSelect<false> | PlayersSelect<true>;
    'training-sessions': TrainingSessionsSelect<false> | TrainingSessionsSelect<true>;
    consents: ConsentsSelect<false> | ConsentsSelect<true>;
    'login-tokens': LoginTokensSelect<false> | LoginTokensSelect<true>;
    devices: DevicesSelect<false> | DevicesSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    rsvps: RsvpsSelect<false> | RsvpsSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Контакт тренера/родителя. 152-ФЗ: минимизация — только для связи.
   */
  phone?: string | null;
  roles: ('admin' | 'coach' | 'parent')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups".
 */
export interface Group {
  id: number;
  name: string;
  /**
   * Кто ведёт группу. Тренер видит и правит только свои группы.
   */
  coaches?: (number | User)[] | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 152-ФЗ: минимизация. Только имя + группа + контакт родителя. Без дат рождения, фото, здоровья, адресов, СНИЛС.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players".
 */
export interface Player {
  id: number;
  name: string;
  group: number | Group;
  /**
   * Аккаунт родителя — контакт и адресат уведомлений. Привязывается при онбординге по magic-link (PR2).
   */
  parent?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-sessions".
 */
export interface TrainingSession {
  id: number;
  group: number | Group;
  startDate: string;
  endDate?: string | null;
  location?: string | null;
  /**
   * Изменение/отмена запускает уведомление родителям (этап M2).
   */
  status: 'planned' | 'changed' | 'cancelled';
  note?: string | null;
  /**
   * Список реально изменившихся полей последней волны (служебное).
   */
  changedFields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Метка последней значимой правки. Coverage и снимок в Notifications.changedAt.
   */
  changedAt?: string | null;
  prevStartDate?: string | null;
  prevLocation?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Юридическая запись согласия на обработку ПДн ребёнка (152-ФЗ). Доступ — только персонал и сам родитель.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consents".
 */
export interface Consent {
  id: number;
  parent: number | User;
  players?: (number | Player)[] | null;
  /**
   * Обязательно. Осознанное согласие законного представителя ребёнка.
   */
  consentGiven: boolean;
  confirmedRepresentative?: boolean | null;
  /**
   * Версия текста согласия/политики на момент подписания (G7 `_v`).
   */
  policyVersion: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "login-tokens".
 */
export interface LoginToken {
  id: number;
  tokenHash: string;
  purpose: 'login' | 'invite';
  email: string;
  user?: (number | null) | User;
  player?: (number | null) | Player;
  expiresAt: string;
  usedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Web-push подписки. Адрес доставки best-effort пуша. Доступ — только свой владелец.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "devices".
 */
export interface Device {
  id: number;
  user: number | User;
  endpoint: string;
  p256dh: string;
  auth: string;
  /**
   * Для диагностики протухания подписки (особенно iOS).
   */
  platform?: string | null;
  userAgent?: string | null;
  lastSuccessAt?: string | null;
  /**
   * Dead-letter: при 410/404 запись удаляется сервисом отправки.
   */
  failureCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Очередь «непринятых» + ack. Первичный гарант доведения (не зависит от пуша). Источник coverage «N из M».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  session: number | TrainingSession;
  parent: number | User;
  /**
   * Какие дети этого родителя затронуты. Имена в payload пуша НЕ уходят (152-ФЗ).
   */
  players: (number | Player)[];
  type: 'changed' | 'cancelled';
  /**
   * delivered→seen→acked. Родитель двигает только вперёд (ack). superseded ставит фан-аут.
   */
  status: 'delivered' | 'seen' | 'acked' | 'superseded';
  /**
   * Снимок session.changedAt. Coverage сверяет с текущей волной сессии.
   */
  changedAt: string;
  /**
   * Диагностика best-effort. Не корректность.
   */
  pushSentAt?: string | null;
  pushResult?: ('ok' | 'failed' | 'skipped') | null;
  seenAt?: string | null;
  ackedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Кто придёт на тренировку. Один ответ на (тренировка × ребёнок). Сводка — на coverage-экране.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rsvps".
 */
export interface Rsvp {
  id: number;
  session: number | TrainingSession;
  player: number | Player;
  parent: number | User;
  response: 'going' | 'not_going';
  /**
   * Для cron-напоминания только нереспондентам (PR9).
   */
  respondedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Новости тренера группе. Не ack-очередь (coverage не затрагивает). Пуш — только по флагу.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: number;
  author?: (number | null) | User;
  group: number | Group;
  title: string;
  /**
   * 152-ФЗ: массовая рассылка — без персональных данных детей в тексте.
   */
  body: string;
  /**
   * best-effort, normal-приоритет. Пуш уходит ОДИН раз — на создании (granularity §6).
   */
  triggersPush?: boolean | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'groups';
        value: number | Group;
      } | null)
    | ({
        relationTo: 'players';
        value: number | Player;
      } | null)
    | ({
        relationTo: 'training-sessions';
        value: number | TrainingSession;
      } | null)
    | ({
        relationTo: 'consents';
        value: number | Consent;
      } | null)
    | ({
        relationTo: 'login-tokens';
        value: number | LoginToken;
      } | null)
    | ({
        relationTo: 'devices';
        value: number | Device;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'rsvps';
        value: number | Rsvp;
      } | null)
    | ({
        relationTo: 'announcements';
        value: number | Announcement;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups_select".
 */
export interface GroupsSelect<T extends boolean = true> {
  name?: T;
  coaches?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players_select".
 */
export interface PlayersSelect<T extends boolean = true> {
  name?: T;
  group?: T;
  parent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-sessions_select".
 */
export interface TrainingSessionsSelect<T extends boolean = true> {
  group?: T;
  startDate?: T;
  endDate?: T;
  location?: T;
  status?: T;
  note?: T;
  changedFields?: T;
  changedAt?: T;
  prevStartDate?: T;
  prevLocation?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consents_select".
 */
export interface ConsentsSelect<T extends boolean = true> {
  parent?: T;
  players?: T;
  consentGiven?: T;
  confirmedRepresentative?: T;
  policyVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "login-tokens_select".
 */
export interface LoginTokensSelect<T extends boolean = true> {
  tokenHash?: T;
  purpose?: T;
  email?: T;
  user?: T;
  player?: T;
  expiresAt?: T;
  usedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "devices_select".
 */
export interface DevicesSelect<T extends boolean = true> {
  user?: T;
  endpoint?: T;
  p256dh?: T;
  auth?: T;
  platform?: T;
  userAgent?: T;
  lastSuccessAt?: T;
  failureCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  session?: T;
  parent?: T;
  players?: T;
  type?: T;
  status?: T;
  changedAt?: T;
  pushSentAt?: T;
  pushResult?: T;
  seenAt?: T;
  ackedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rsvps_select".
 */
export interface RsvpsSelect<T extends boolean = true> {
  session?: T;
  player?: T;
  parent?: T;
  response?: T;
  respondedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  author?: T;
  group?: T;
  title?: T;
  body?: T;
  triggersPush?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}